version: '3.8' # Use a compatible version with your Docker Compose and Docker Engine

services:
  airflow:
    image: apache/airflow:2.0.0-python3.8
    container_name: airflow
    entrypoint: /bin/bash
    command: >
      -c 
      "airflow db init &&
       airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org;
       airflow webserver &
       airflow scheduler"
    ports:
      - "8080:8080"
    volumes:
      -./Chapter2Example.py:/opt/airflow/dags/Chapter2Example.py
